"""Initial schema with documents and chunks tables

Revision ID: 1367bf7a9116
Revises: 
Create Date: 2026-01-21 10:49:42.099232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1367bf7a9116'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True, comment='Original source: URL or file path'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'parsing', 'parsed', 'chunking', 'chunked', 'embedding', 'completed', 'failed', name='documentstatus'), nullable=False),
    sa.Column('status_details', sa.Text(), nullable=True, comment='Error messages or status information from pipeline stages'),
    sa.Column('chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Serialized chunks before embedding (temporary storage)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Text(), nullable=False, comment='UUID linking to langchain_pg_embedding table'),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Position in parent document (0-indexed)'),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Header hierarchy, semantic boundaries, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
